apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-react
  labels:
    app: orbit-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-react
  template:
    metadata:
      labels:
        app: orbit-react
    spec:
      containers:
      - name: react
        image: orbit-react:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-react-service
spec:
  selector:
    app: orbit-react
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
