apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-fastapi
  labels:
    app: orbit-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-fastapi
  template:
    metadata:
      labels:
        app: orbit-fastapi
    spec:
      containers:
      - name: fastapi
        image: orbit-fastapi:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-fastapi-service
spec:
  selector:
    app: orbit-fastapi
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
