apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-go
  labels:
    app: orbit-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-go
  template:
    metadata:
      labels:
        app: orbit-go
    spec:
      containers:
      - name: go
        image: orbit-go:latest
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-go-service
spec:
  selector:
    app: orbit-go
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: NodePort
