apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-rust
  labels:
    app: orbit-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-rust
  template:
    metadata:
      labels:
        app: orbit-rust
    spec:
      containers:
      - name: rust
        image: orbit-rust:latest
        ports:
        - containerPort: 7500
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-rust-service
spec:
  selector:
    app: orbit-rust
  ports:
  - protocol: TCP
    port: 7500
    targetPort: 7500
  type: NodePort
