apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-spring
  labels:
    app: orbit-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-spring
  template:
    metadata:
      labels:
        app: orbit-spring
    spec:
      containers:
      - name: spring
        image: orbit-spring:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-spring-service
spec:
  selector:
    app: orbit-spring
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
