environments:
  - name: dev
    description: Development environment
    variables:
      - name: BRANCH_NAME
        description: The branch name
        type: string
        default: develop
  - name: prod
    description: Production environment
    variables:
      - name: BRANCH_NAME
        description: The branch name
        type: string
        default: main
