apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-cpp
  labels:
    app: orbit-cpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-cpp
  template:
    metadata:
      labels:
        app: orbit-cpp
    spec:
      containers:
      - name: cpp
        image: orbit-cpp:latest
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-cpp-service
spec:
  selector:
    app: orbit-cpp
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort
