apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-vaadin
  labels:
    app: orbit-vaadin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbit-vaadin
  template:
    metadata:
      labels:
        app: orbit-vaadin
    spec:
      containers:
      - name: vaadin
        image: orbit-vaadin:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: orbit-vaadin-service
spec:
  selector:
    app: orbit-vaadin
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort
